### ISSUE TITLE
during demo-save-and-eval.py, get errors

### ISSUE THREAD

**Issue by kentaroy47** [kentaroy47/DatasetCulling#2]
The script fails in the last part of dataset-culling.py, during demo-save-and-eval.py.

```
load checkpoint models/res18/pascal_voc_200-jackson2/faster_rcnn_1_20.pth
load model successfully!
load checkpoint models/res18/pascal_voc_200-jackson2/faster_rcnn_1_20.pth
demo-and-eval-save.py:384: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  im_data = Variable(im_data, volatile=True)
demo-and-eval-save.py:385: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  im_info = Variable(im_info, volatile=True)
demo-and-eval-save.py:386: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  num_boxes = Variable(num_boxes, volatile=True)
demo-and-eval-save.py:387: UserWarning: volatile was removed and now has no effect. Use `with torch.no_grad():` instead.
  gt_boxes = Variable(gt_boxes, volatile=True)
Loaded Photo: 10806 images.
detection for  __background__02s       
Traceback (most recent call last):
  File "demo-and-eval-save.py", line 694, in <module>
    BBGTs = truth_boxes[ncls][:]
IndexError: list index out of range
```

**Comment by kentaroy47** [comment]
@kentaroy47 
this is because ground truth answers are not supplied to the model (and to the repo yet).
This is a work undergoing, let me work on this.

**Comment by alpereninci** [comment]
load checkpoint models/res18/pascal_voc_200-jackson2/faster_rcnn_1_20.pth
load model successfully!
load checkpoint models/res18/pascal_voc_200-jackson2/faster_rcnn_1_20.pth
Loaded Photo: 3602 images.
/home/mmrg/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
Traceback (most recent call last):   
  File "demo-and-eval-save.py", line 668, in <module>
    for i in range(len(truth_boxes[:])):
NameError: name 'truth_boxes' is not defined
total time taken: 961.7539942264557

@kentaroy47 any update about the problem?

**Comment by kentaroy47** [comment]
@alpereninci Yes, you need to generate the baseline results by resnet-101 models. It would be great if you can supply the labels yourself by running res101 models on your eval data. Sorry I lost access to the server having the pkl file and cannot upload this quickly.

Since this repo is quite old, I can rework based on modern detectors like yolov5 but I may not have the time at the moment..
